"""
oauth_server.py — Local Flask server for Discord OAuth2 member registration.

How it works:
  1. Members click your registration link (generated by get_auth_url())
  2. They authorize on Discord's website
  3. Discord redirects them to the GitHub Pages callback page
  4. That page POSTs the auth code to this server (running on localhost:5173)
  5. This server exchanges the code for an access token and stores it
  6. On restore, stored tokens are used to re-add members via Discord API
"""

from flask import Flask, request, jsonify, Response
import urllib.request
import urllib.parse
import json
import os
import time
import threading

PORT = 5173
REDIRECT_URI = "https://rglov.github.io/discord-denuker/callback"
TOKEN_FILE    = os.path.join(os.path.expanduser("~"), ".denuker_tokens.json")
DISCORD_TOKEN_URL = "https://discord.com/api/oauth2/token"
DISCORD_USER_URL  = "https://discord.com/api/users/@me"

# Allowed CORS origin — the GitHub Pages page that POSTs codes to us
_CORS_ORIGIN = "https://rglov.github.io"

_client_id:     str = ""
_client_secret: str = ""
_log_callback        = None  # fn(str) — progress messages back to GUI

app = Flask(__name__)


# ── Public API ────────────────────────────────────────────────────────────────

def start(client_id: str, client_secret: str, log_fn=None) -> threading.Thread:
    """Start the OAuth2 registration server in a background daemon thread."""
    global _client_id, _client_secret, _log_callback
    _client_id     = client_id.strip()
    _client_secret = client_secret.strip()
    _log_callback  = log_fn

    import logging
    log = logging.getLogger("werkzeug")
    log.setLevel(logging.ERROR)   # suppress Flask's request logs

    t = threading.Thread(
        target=lambda: app.run(host="127.0.0.1", port=PORT, debug=False, use_reloader=False),
        daemon=True,
        name="oauth-server",
    )
    t.start()
    return t


def get_auth_url(client_id: str) -> str:
    """Return the Discord OAuth2 authorization URL to share with members."""
    params = urllib.parse.urlencode({
        "client_id":     client_id,
        "redirect_uri":  REDIRECT_URI,
        "response_type": "code",
        "scope":         "guilds.join identify",
        "prompt":        "none",   # skip re-auth if already authorized
    })
    return f"https://discord.com/api/oauth2/authorize?{params}"


def get_registered_count() -> int:
    return len(load_tokens())


def load_tokens() -> dict:
    try:
        if os.path.exists(TOKEN_FILE):
            with open(TOKEN_FILE) as f:
                return json.load(f)
    except Exception:
        pass
    return {}


def save_tokens(tokens: dict) -> None:
    with open(TOKEN_FILE, "w") as f:
        json.dump(tokens, f, indent=2)
    try:
        os.chmod(TOKEN_FILE, 0o600)   # restrict to owner only
    except Exception:
        pass


# ── Token helpers ─────────────────────────────────────────────────────────────

def refresh_token_sync(token_data: dict, client_id: str, client_secret: str) -> dict | None:
    """Refresh an expired (or near-expired) Discord access token. Returns updated dict or None."""
    try:
        result = _http_post(DISCORD_TOKEN_URL, {
            "client_id":     client_id,
            "client_secret": client_secret,
            "grant_type":    "refresh_token",
            "refresh_token": token_data["refresh_token"],
        })
        if "error" in result:
            return None
        return {
            **token_data,
            "access_token":  result["access_token"],
            "refresh_token": result.get("refresh_token", token_data["refresh_token"]),
            "expires_at":    time.time() + result.get("expires_in", 604800),
        }
    except Exception:
        return None


# ── Flask routes ──────────────────────────────────────────────────────────────

@app.after_request
def _add_cors(response):
    response.headers["Access-Control-Allow-Origin"]  = _CORS_ORIGIN
    response.headers["Access-Control-Allow-Methods"] = "POST, GET, OPTIONS"
    response.headers["Access-Control-Allow-Headers"] = "Content-Type"
    return response


@app.route("/exchange", methods=["POST", "OPTIONS"])
def exchange():
    """Exchange an auth code for a user token and store it."""
    if request.method == "OPTIONS":
        return Response(status=204)

    body = request.get_json(silent=True) or {}
    code = body.get("code") or request.form.get("code", "").strip()
    if not code:
        return jsonify({"success": False, "error": "No auth code provided"}), 400

    try:
        # Step 1 — exchange code for token
        token_data = _http_post(DISCORD_TOKEN_URL, {
            "client_id":     _client_id,
            "client_secret": _client_secret,
            "grant_type":    "authorization_code",
            "code":          code,
            "redirect_uri":  REDIRECT_URI,
        })
        if "error" in token_data:
            return jsonify({"success": False,
                            "error": f"Discord error: {token_data['error']}"}), 400

        access_token = token_data["access_token"]

        # Step 2 — fetch user identity
        user = _http_get(DISCORD_USER_URL, access_token)
        user_id  = user["id"]
        username = user.get("username", "Unknown")

        # Step 3 — persist
        tokens = load_tokens()
        tokens[user_id] = {
            "access_token":  access_token,
            "refresh_token": token_data.get("refresh_token"),
            "expires_at":    time.time() + token_data.get("expires_in", 604800),
            "username":      username,
        }
        save_tokens(tokens)

        if _log_callback:
            _log_callback(f"  ✅ Member registered: {username}")

        return jsonify({"success": True, "username": username})

    except Exception as exc:
        if _log_callback:
            _log_callback(f"  ⚠ Registration error: {exc}")
        return jsonify({"success": False, "error": str(exc)}), 500


@app.route("/status")
def status():
    tokens = load_tokens()
    return jsonify({
        "registered": len(tokens),
        "members": [{"id": k, "username": v.get("username")} for k, v in tokens.items()],
    })


@app.route("/health")
def health():
    return jsonify({"ok": True})


# ── Private helpers ───────────────────────────────────────────────────────────

def _http_post(url: str, data: dict) -> dict:
    encoded = urllib.parse.urlencode(data).encode()
    req = urllib.request.Request(url, data=encoded, method="POST")
    req.add_header("Content-Type", "application/x-www-form-urlencoded")
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read())


def _http_get(url: str, bearer: str) -> dict:
    req = urllib.request.Request(url)
    req.add_header("Authorization", f"Bearer {bearer}")
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read())
